### ISSUE TITLE
Code 400 : ONVIF Media Service

### ISSUE THREAD

**Issue by sdvillaruziii** [chengtengfei/onvif-simple#1]
![image](https://user-images.githubusercontent.com/44084988/84346202-17cf1180-abb8-11ea-9b59-cb6df2b4bd69.png)

**Comment by chengtengfei** [comment]
请问是不是在onvif-simple的基础上进行了修改？若是 能否把修改后的代码和调用示例发送至我的邮箱1062011419@qq.com，我来查看是哪里出了问题。

**Comment by chengtengfei** [comment]
@sdvillaruziii 请问是不是在onvif-simple的基础上进行了修改？若是 能否把修改后的代码和调用示例发送至我的邮箱1062011419@qq.com，我来查看是哪里出了问题。

**Comment by sdvillaruziii** [comment]
> @sdvillaruziii 请问是不是在onvif-simple的基础上进行了修改？若是 能否把修改后的代码和调用示例发送至我的邮箱[1062011419@qq.com](mailto:1062011419@qq.com)，我来查看是哪里出了问题。

I've emailed you.

**Comment by chengtengfei** [comment]
@sdvillaruziii I guess that you change the code segment in `com.github.chengtengfei.onvif.service.OnvifService#getVideoInfo()`, it seems exception appeared when getting camera profile. But i am not sure what goes wrong, can you offer response body content? Meanwhile, you can use the fully functional software called ONVIF Device Test Tool to test your camera, you can get the software from https://send.firefox.com/download/0c782123b65c1d7c/#Yk5VsZBaNViGKxvpkqwtTQ, the link will expire 7 days later.

**Comment by sdvillaruziii** [comment]
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope
    xmlns:s="http://www.w3.org/2003/05/soap-envelope">
    <s:Header>
        <wsse:Security
            xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
            xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
            <wsse:UsernameToken>
                <wsse:Username>admin</wsse:Username>
                <wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">KwuTIHmilNIxvfbJ0Mm2AK3bOe0=</wsse:Password>
                <wsse:Nonce>eUpkUFhZbUlQdzVIb2llbXlGSXM=</wsse:Nonce>
                <wsu:Created>2020-06-11T11:37:37.683Z</wsu:Created>
            </wsse:UsernameToken>
        </wsse:Security>
    </s:Header>
    <s:Body
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<GetProfiles xmlns="http://www.onvif.org/ver10/media/wsdl"/>
</s:Body>
</s:Envelope>

I didn't change anything in the code.

**Comment by sdvillaruziii** [comment]
> @sdvillaruziii I guess that you change the code segment in `com.github.chengtengfei.onvif.service.OnvifService#getVideoInfo()`, it seems exception appeared when getting camera profile. But i am not sure what goes wrong, can you offer response body content? Meanwhile, you can use the fully functional software called ONVIF Device Test Tool to test your camera, you can get the software from https://send.firefox.com/download/0c782123b65c1d7c/#Yk5VsZBaNViGKxvpkqwtTQ, the link will expire 7 days later.

This is the result from the tool.
![image](https://user-images.githubusercontent.com/44084988/84375851-cf7c1780-abe8-11ea-8158-4a86bd830fa7.png)

**Comment by chengtengfei** [comment]
From your information, it seems your camera has different behaviors with cameras uesd to test this project. I want to get more information, you can change the code in `com.github.chengtengfei.onvif.util.OkHttpUtils#okHttp3XmlPost()`, change 
```
        if (response.isSuccessful()) {
            String s = response.body().string();
            return s;
        } else if (response.code() >= 400 && response.code() < 500) {
            throw new Exception("设备认证失败(用户名或密码错误)");
        } else {
            LOGGER.debug("返回不成功:  "+ response.body().string());
            throw new Exception("返回不成功");
        }
```
to 
```
        if (response.isSuccessful()) {
            String s = response.body().string();
            return s;
        } else if (response.code() > 400 && response.code() < 500) {
            throw new Exception("设备认证失败(用户名或密码错误)");
        } else {
            LOGGER.debug("返回不成功:  "+ response.body().string());
            throw new Exception("返回不成功");
        }
```
,then enable the debug model. When you get the 400 response, it will print the response body at `LOGGER.debug("返回不成功:  "+ response.body().string());`, the log maybe carry the failing reason, then show me the log, thank you.

**Comment by chengtengfei** [comment]
@sdvillaruziii 
From your information, it seems your camera has different behaviors with cameras uesd to test this project. I want to get more information, you can change the code in `com.github.chengtengfei.onvif.util.OkHttpUtils#okHttp3XmlPost()`, change 
```
        if (response.isSuccessful()) {
            String s = response.body().string();
            return s;
        } else if (response.code() >= 400 && response.code() < 500) {
            throw new Exception("设备认证失败(用户名或密码错误)");
        } else {
            LOGGER.debug("返回不成功:  "+ response.body().string());
            throw new Exception("返回不成功");
        }
```
to 
```
        if (response.isSuccessful()) {
            String s = response.body().string();
            return s;
        } else if (response.code() > 400 && response.code() < 500) {
            throw new Exception("设备认证失败(用户名或密码错误)");
        } else {
            LOGGER.debug("返回不成功:  "+ response.body().string());
            throw new Exception("返回不成功");
        }
```
,then enable the debug model. When you get the 400 response, it will print the response body at `LOGGER.debug("返回不成功:  "+ response.body().string());`, the log maybe carry the failing reason, then show me the log, thank you.

**Comment by sdvillaruziii** [comment]
> @sdvillaruziii
> From your information, it seems your camera has different behaviors with cameras uesd to test this project. I want to get more information, you can change the code in `com.github.chengtengfei.onvif.util.OkHttpUtils#okHttp3XmlPost()`, change
> 
> ```
>         if (response.isSuccessful()) {
>             String s = response.body().string();
>             return s;
>         } else if (response.code() >= 400 && response.code() < 500) {
>             throw new Exception("设备认证失败(用户名或密码错误)");
>         } else {
>             LOGGER.debug("返回不成功:  "+ response.body().string());
>             throw new Exception("返回不成功");
>         }
> ```
> 
> to
> 
> ```
>         if (response.isSuccessful()) {
>             String s = response.body().string();
>             return s;
>         } else if (response.code() > 400 && response.code() < 500) {
>             throw new Exception("设备认证失败(用户名或密码错误)");
>         } else {
>             LOGGER.debug("返回不成功:  "+ response.body().string());
>             throw new Exception("返回不成功");
>         }
> ```
> 
> ,then enable the debug model. When you get the 400 response, it will print the response body at `LOGGER.debug("返回不成功: "+ response.body().string());`, the log maybe carry the failing reason, then show me the log, thank you.

Hi. This is the result.
![image](https://user-images.githubusercontent.com/44084988/84584866-29abf100-ae12-11ea-9966-6fa390f8e5a2.png)

**Comment by sdvillaruziii** [comment]
> @sdvillaruziii
> From your information, it seems your camera has different behaviors with cameras uesd to test this project. I want to get more information, you can change the code in `com.github.chengtengfei.onvif.util.OkHttpUtils#okHttp3XmlPost()`, change
> 
> ```
>         if (response.isSuccessful()) {
>             String s = response.body().string();
>             return s;
>         } else if (response.code() >= 400 && response.code() < 500) {
>             throw new Exception("设备认证失败(用户名或密码错误)");
>         } else {
>             LOGGER.debug("返回不成功:  "+ response.body().string());
>             throw new Exception("返回不成功");
>         }
> ```
> 
> to
> 
> ```
>         if (response.isSuccessful()) {
>             String s = response.body().string();
>             return s;
>         } else if (response.code() > 400 && response.code() < 500) {
>             throw new Exception("设备认证失败(用户名或密码错误)");
>         } else {
>             LOGGER.debug("返回不成功:  "+ response.body().string());
>             throw new Exception("返回不成功");
>         }
> ```
> 
> ,then enable the debug model. When you get the 400 response, it will print the response body at `LOGGER.debug("返回不成功: "+ response.body().string());`, the log maybe carry the failing reason, then show me the log, thank you.

Hi. This is the result.

![image](https://user-images.githubusercontent.com/44084988/84585005-7e9c3700-ae13-11ea-8276-9d0b9f64532e.png)

**Comment by chengtengfei** [comment]
@sdvillaruziii 
Hi, it maybe a timezone problem, change the method `com.github.chengtengfei.onvif.util.EncryptUtils#created()` to
```
private static String created() {
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
        format.setTimeZone(TimeZone.getTimeZone("UTC"));
        return format.format(new Date());
    }
```
and retry once. Thanks!

**Comment by sdvillaruziii** [comment]
> format.setTimeZone(TimeZone.getTimeZone("UTC"));

Still the same error.

**Comment by sdvillaruziii** [comment]
I made it work, the usertoken needs to be recreated.

**Comment by sdvillaruziii** [comment]
> I made it work, the usertoken needs to be recreated every request because the timestamp is changing.
